Imported Debian patch 3.9.20060704-4

diff --git a/debian/isdnutils-base.postrm b/debian/isdnutils-base.postrm
--- a/debian/isdnutils-base.postrm
+++ b/debian/isdnutils-base.postrm
@@ -5,10 +5,11 @@ set -e
 
 case "$1" in
        purge)
-	 rmdir /etc/isdn 2>/dev/null || true
-	 if [ -d /etc/isdn ]; then
-	 	echo "There are still files in /etc/isdn/ that you may want to remove manually."
-	 fi
+         set +e # don't exit on error
+	 rmdir --ignore-fail-on-non-empty /etc/isdn &&
+            [ -d /etc/isdn ] &&
+            echo "There are still files in /etc/isdn/ that you may want to remove manually."
+         set -e
          ;;
 
        remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
